### ISSUE TITLE
Missing bsd/readpassphrase.h

### ISSUE THREAD

**Issue by count0x30** [zelea2/wd-passport#1]
Hi, trying to compile on Linux Mint 22.1 and encountering this:

```
$ make
gcc -Iinc -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
 	-Wall -O2 -c wd-passport.c -o wd-passport.o	
wd-passport.c:15:10: fatal error: bsd/readpassphrase.h: No such file or directory
   15 | #include <bsd/readpassphrase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Would love to get this program working, because I haven't found anything else like it!

**Comment by zelea2** [comment]
If you are on debian or similar 'sudo apt install libbsd-dev'

**Comment by count0x30** [comment]
Thanks, that got `wd-passport` to compile.  

However,  I can't get it to unlock my WD My Passport Ultra drive, even when I've just set the password to "test".  The program also won't read the drive label or the password hint, though I can see the hint in the drive's response when using the -v flag.

Also, in case you revisit this project, my suggestion is to allow the -u flag to work without a parameter, so that on the next line `wd-passport` can ask for the password.  This way, it can be hidden from view and kept out of the shell history.
